server:
 port: 9191
 
spring:
  application: 
   name: api-gateway-service
   
   cloud:
    gateway:
     routes:
      -id: USER-SERVICE
       uri:lb://user-service
      predicates:
       -path=/amazon/user/**
       
      -id1: PRODUCT-SERVICE
       uri:lb://product-service
      predicates1:
       -path=/amazon/prducts/**
       
      -id2: ADDRESS-SERVICE
       uri:lb://address-service
      predicates2:
        -path=/amazon/user_address/**
       
     
       
